apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-app-sm
  namespace: default
  labels:
    release: prometheus-operator
spec:
  endpoints:
    - interval: 10s
      targetPort: 8080
      path: /metrics
  namespaceSelector:
    matchNames:
      - scale-test
  selector:
    matchLabels:
      prometheus-monitored: "true"
