replicaCount: 1

image:
  repository: shestera/scaletestapp
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    memory: "64Mi"
  requests:
    memory: "64Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetMemoryUtilizationPercentage: 15

